// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Survivor.Models;

namespace Survivor.Migrations
{
    [DbContext(typeof(SurvivorContext))]
    [Migration("20191028183638_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Survivor.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerDays");

                    b.Property<string>("PlayerName");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PlayerDays = 117,
                            PlayerName = "Boston Rob"
                        });
                });

            modelBuilder.Entity("Survivor.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SeasonName");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            SeasonName = "Marquesas"
                        });
                });

            modelBuilder.Entity("Survivor.Models.SeasonPlayer", b =>
                {
                    b.Property<int>("SeasonPlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerId");

                    b.Property<int>("SeasonId");

                    b.HasKey("SeasonPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonPlayers");

                    b.HasData(
                        new
                        {
                            SeasonPlayerId = 1,
                            PlayerId = 1,
                            SeasonId = 1
                        });
                });

            modelBuilder.Entity("Survivor.Models.SeasonPlayer", b =>
                {
                    b.HasOne("Survivor.Models.Player", "Player")
                        .WithMany("Seasons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survivor.Models.Season", "Season")
                        .WithMany("Players")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
