// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Survivor.Models;

namespace Survivor.Migrations
{
    [DbContext(typeof(SurvivorContext))]
    [Migration("20191028212253_UpdatedNamesAgain")]
    partial class UpdatedNamesAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Survivor.Models.Appearance", b =>
                {
                    b.Property<int>("AppearanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaysPerSeason");

                    b.Property<int>("PlayerId");

                    b.Property<int>("SeasonId");

                    b.HasKey("AppearanceId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Appearances");

                    b.HasData(
                        new
                        {
                            AppearanceId = 1,
                            DaysPerSeason = 0,
                            PlayerId = 1,
                            SeasonId = 1
                        });
                });

            modelBuilder.Entity("Survivor.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlayerName");

                    b.Property<int>("TotalDays");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PlayerName = "Boston Rob",
                            TotalDays = 117
                        });
                });

            modelBuilder.Entity("Survivor.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SeasonName");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            SeasonName = "Marquesas"
                        });
                });

            modelBuilder.Entity("Survivor.Models.Appearance", b =>
                {
                    b.HasOne("Survivor.Models.Player", "Player")
                        .WithMany("SeasonsPlayed")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survivor.Models.Season", "Season")
                        .WithMany("PlayersInSeason")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
